### ISSUE TITLE
GurobiError: Invalid argument to Model.addConstr

### ISSUE THREAD

**Issue by hiron-r** [kevinrussellmoy/AA222FinalProject#1]
line 125, in <module>
    m.addConstr(E[0] == 0.5 * E_nom)

  File "src\gurobipy\model.pxi", line 3451, in gurobipy.Model.addConstr

  File "src\gurobipy\model.pxi", line 3355, in gurobipy.Model.__addConstr

GurobiError: Invalid argument to Model.addConstr

![image](https://user-images.githubusercontent.com/62418149/178942106-9f9e5b8e-4890-48da-bd11-ff39c5edd55c.png)

Please kindly solve the error.

**Comment by kevinrussellmoy** [comment]
Should be fixed now. Changed P_nom and E_mon to Var (single variables) instead of MVar (multi-dim variables); also changed the simultaneous charge and discharge constraint to avoid MVar/Var conflicts there. Also added some more description on the cost functions. Hope this helps!

**Comment by hiron-r** [comment]
Thank you so much, Dr. Moy. It works
