### ISSUE TITLE
Some data csv files could not be found

### ISSUE THREAD

**Issue by 2345as** [kevinrussellmoy/AA222FinalProject#3]
Some data csv files could not be found, 15minute_data_california/15minute_data_california.csv, /metadata.csv

**Comment by kevinrussellmoy** [comment]
Hello,

This is intentional. These CSV files are only needed to generate resi_load.csv, as shown in resi_data.py. However, the main focus of this repo is in the optimization of dispatch as indicated by the README. Thank you.
